### ISSUE TITLE
Verbesserungsvorschlag: "Herkunft" auch auf Bilddetailseite anzeigen

### ISSUE THREAD

**Issue by elyawp** [okfde/mein-stadtarchiv#1]
Auf den Suchergebnisseiten bzw. Filterlisten vom Typ https://mein-stadtarchiv.de/recherche?category=5a266f0d034472135fe94717&media=1 erscheint als Metadaten die Info zur Herkunft eines Bildes. 

Dieser Wert wird auf der Detailseite nicht mehr angezeigt, Bsp.
https://mein-stadtarchiv.de/document/5a266f0e034472135fe948bb 

Wäre jedoch sinnvoll, um die Metadaten alle beisammen zu haben. 

Danke!

**Comment by the-infinity** [comment]
Huch, da fehlte doch glatt die Feldausgabe. Fixed mit https://github.com/okfde/mein-stadtarchiv/commit/8c9451762179a0bacc4b00a9c0265de9daf2d8e9 .
