### ISSUE TITLE
Verbesserungsvorschlag: Breadcrumbtrail anklickbar machen

### ISSUE THREAD

**Issue by elyawp** [okfde/mein-stadtarchiv#2]
In Detailseiten vom Typ https://mein-stadtarchiv.de/document/5a266f0e034472135fe94927 gibt es einen Kategorie-Breadcrumb. Diesen anklickbar zu machen wäre sinnvoll, so daß man in die entsprechende Kategorie zurückspringen kann. Derzeit muß man den Browser-Zurückbutton nutzen.

**Comment by the-infinity** [comment]
Gute Idee. Realisiert in https://github.com/okfde/mein-stadtarchiv/commit/6d87174446eec50d72dad9915c8049241e862f2f .

**Comment by elyawp** [comment]
cool!
